"""add phone number

Revision ID: 74e1bc224bcf
Revises: 1547fcc79f14
Create Date: 2024-02-01 10:00:56.998787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e1bc224bcf'
down_revision: Union[str, None] = '1547fcc79f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_NO', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_NO')
    # ### end Alembic commands ###
